### ISSUE TITLE
Question ต่างๆในเกม

### ISSUE THREAD

**Issue by OHMSIRAPOB** [Tiggers123/SUNSUNCHESS#11]

**Comment by PantawatB** [comment]
คำถาม 
คิบูตสิจิ มุซัน เป็นปีศาจในสมัยใด
เฮอัง ยุคมูโรมาจิ, เซ็งโงกุ และ ฮิงาชิยามะ
คิบูตสิจิ มุซัน ตอนเป็นมนุษย์ใช้ชื่อว่าอะไร
Tsukihiko Makomo Tamayo Shaji
ใครอายุมากที่สุด ในเสาหลัก
เกียวเม ซาเนมิ เท็นเง็น เคียวจูโร่
ใครอายุน้อยที่สุดในเสาหลัก
มุอิจิโร่ ชิโนบุ มิตซึริ กิยู
มุอิจิโร่ใช้เวลากี่เดือนในการเป็นเสาหลัก
2 เดือน 2 อาทิตย์ 2 ปี 7 วัน
โทมิโอกะ กิยู best friend
ซาบิโตะ ทันจิโร่ ชิโนบุ มิตซึริ
กลุ่มพิฆาตอสูรมีกี่ขั้น
[10 11 9 12]
ก่อนที่เคียวจูโร่จากไปฝากบอกอะไรพ่อตัวเอง
Take care of himself ล้างแค้น ไม่ต้องห่วงผม ฝากทันจิโร่
เสาหลักที่ชอบแมว
เกียวเม กิยู มุอิจิโร่ ชิโนบุ
ชิโนบุว่างๆชอบทำอะไร
เล่าเรื่องผี นอน กิน คุยกับเสาหลักคนอื่น
