### ISSUE TITLE
แบ่งหน้าที่

### ISSUE THREAD

**Issue by Tiggers123** [Tiggers123/SUNSUNCHESS#4]
กำหนดบทบาทที่จะรับผิดชอบของสมาชิกแต่ละคนในกลุ่ม

**Comment by OHMSIRAPOB** [comment]
โอม—>วางแผนโปรเจค จัดการ GitHub เขียนโค้ด
ก้อง—>ทำโค้ดส่วนคำถาม รวบรวมสมาชิกในทีมคุยโปรเจค
ปั๋น—>เขียนโค้ดส่วนที่เลือกหัวข้อของquiz แก้โค้ด tester 
กร—>เขียนโค้ด tester
บอน—>เขียนโค้ด tester
หน้าที่คร่าวๆเบื้องต้นของแต่ละคน
