### ISSUE TITLE
รายละเอียดของเกมที่จะสร้าง

### ISSUE THREAD

**Issue by Tiggers123** [Tiggers123/SUNSUNCHESS#5]
การเก็บคะเเนน การหักคะเเนน การตัดสินผู้ชนะ วิธีการเล่น กฎกติกาพิเศษ

**Comment by Khongpop3147** [comment]
![game rules](https://user-images.githubusercontent.com/110969658/221500666-57b2a059-9079-4152-932f-93122fc1622e.jpg)
