### ISSUE TITLE
สรุปความคืบความหน้าของงาน

### ISSUE THREAD

**Issue by Tiggers123** [Tiggers123/SUNSUNCHESS#7]

**Comment by Miracles01** [comment]
void question1() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "      *****" << endl;
	cout << "                                                                                     ***********************************" << endl; 
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 1"<< endl;
		cout << "How many siblings does Tanjiro Kamado have in total?" << endl;
		cout << "[1] 4"<<endl;
		cout << "[2] 6" << endl;
		cout << "[3] 5" << endl;
		cout << "[4] 7" << endl;
		string answer;
		cout << endl;
    	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
		cin >> answer;
		//limiting the answers of the user
		if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
		{
			if (answer == "2")
			{
				total_score += 10;
				correct_answer += 1;
				cout << "C O R R E C T   A N S W E R !!!" << endl;
				cout << "You got 10 points out of 10." << endl;
			}
			else if (answer == "1" || answer == "3" || answer == "4")
			{
				cout << "W R O N G  A N S W E R !!!" << endl;
				cout << "You got 0 points out of 10." << endl;
			}
			cout << endl;
			system("pause");
			system("cls");
		}
		else 
		{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question1();
		}
}
void question2() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 2" << endl;
	cout << "Which of the characters below have claimed that they are “a living being who's infinitely close to perfection”?" << endl;
	cout << "[1] Rui" << endl;
	cout << "[2] Akaza" << endl;
	cout << "[3] Ruka Rengoku" << endl;
	cout << "[4] Muzan kibutsuji" << endl;
	string answer;
	cout<<endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "4")
		{
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
		}
		else if (answer == "1" || answer == "2" || answer == "3")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
		}
			cout << endl;
			system("pause");
			system("cls");
		}
	else
	{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question2();
	}
	
}
void question3() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 3" << endl;
	cout << "Who has already been revealed to have a very hard head?" << endl;
	cout << "[1] Kamado Nezuko" << endl;
	cout << "[2] Tanjiro's mother (unknown writer" << endl;
	cout << "[3] Usui Tengen" << endl;
	cout << "[4] Agatsuma Zenitsu" << endl;
	string answer;
	cout << endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "2") {
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
		}
		else if (answer == "1" || answer == "4" || answer == "3")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
		}
			cout << endl;
			system("pause");
			system("cls");
	}
	else
	{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question3();
	}
}
void question4() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 4" << endl; 
	cout << "Which waning beast appears in the Eternal Railroad" << endl;
	cout << "[1] No waning beasts appeared at all." << endl;
	cout << "[2] Rui" << endl;
	cout << "[3] Akasa" << endl;
	cout << "[4] Enmu" << endl;
	string answer;
	cout << endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "4") {
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
		}
		else if (answer == "1" || answer == "2" || answer == "3")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
		}
			cout << endl;
			system("pause");
			system("cls");
	}
	else
	{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question4();
	}
}
void question5() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 5" << endl; 
	cout << "Who is known as the “Demon Child”?" << endl;
	cout << "[1] Akaza" << endl;
	cout << "[2] Enmu" << endl;
	cout << "[3] Obanai lguro" << endl;
	cout << "[4] Genyaa shinazugawa" << endl;
	string answer;
	cout << endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "2") {
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
		}
		else if (answer == "1" || answer == "3" || answer == "4")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
		}
		cout << endl;
		system("pause");
		system("cls");
	}
		else
		{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question5();
		}
	
}
void question6() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 6" << endl;
	cout << "Who does Iguro Obanai secretly like?" << endl;
	cout << "[1] Kamado Tanjiro" << endl;
	cout << "[2] Kanroji Mitsuri2" << endl;
	cout << "[3] Kojo Shinobu" << endl;
	cout << "[4] Tomioka Giyu" << endl;
	string answer;
	cout << endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "2") 
		{
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
			
		}
		else if (answer == "1" || answer == "3" || answer == "4")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
			
		}
			cout << endl;
			system("pause");
			system("cls");
		}
		else
		{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question6();
		}
}
void question7() {
	cout << "                                                                                     ***********************************" << endl;
	cout << "                                                                                     *****      TOTAL SCORE:" << total_score << "     *****" << endl;
	cout << "                                                                                     ***********************************" << endl;
	cout << "\t\t\t\t\t  Q U E S T I O N  No. 7" << endl;  
	cout << "Who is Zenitsu's wife?" << endl;
	cout << "[1] Suma" << endl;
	cout << "[2] Kamado Nezuko" << endl;
	cout << "[3] Makio" << endl;
	cout << "[4] Zenitsu has no wife;" << endl;
	string answer;
	cout << endl;
	cout << "\t\t\t\t\tENTER YOUR CHOICE: ";
	cin >> answer;
	if (answer == "1" || answer == "2" || answer == "3" || answer == "4")
	{
		if (answer == "2") {
			total_score += 10;
			correct_answer += 1;
			cout << "C O R R E C T   A N S W E R !!!" << endl;
			cout << "You got 10 points out of 10." << endl;
		}
		else if (answer == "1" || answer == "3" || answer == "4")
		{
			cout << "W R O N G  A N S W E R !!!" << endl;
			cout << "You got 0 points out of 10." << endl;
			
		}
			cout << endl;
			system("pause");
			system("cls");
	}
		else
		{
			system("cls");
			cout << "\t\t*************************************************************************************" << endl;
			cout << "\t\t****           P L E A S E  I N P U T  C O R R E C T  V A L U E !                ****" << endl;
			cout << "\t\t*************************************************************************************" << endl;
			cout << endl;
			question7();
		}
}

**Comment by OHMSIRAPOB** [comment]
ตอนนี้ภาพรวมของเกมเกือบเสร็จทั้งหมดแล้ว เหลือเพียงตกแต่งภายในเกม แก้ไขบัคต่างๆภายในเกม
