### ISSUE TITLE
ระบบ Main Menu

### ISSUE THREAD

**Issue by OHMSIRAPOB** [Tiggers123/SUNSUNCHESS#9]

**Comment by Miracles01** [comment]
#include <iostream>
#include <string>
#include <conio.h>
#include <stdio.h>
using namespace std;

int choice;
void menu(){
     // Display the main menu options
    system("color 0B");//Color XY,X = สีของพื้นหลัง,Y=สีของข้อความ
    system("cls");
            cout<<"\t\t\t\t =========================================================="<< " \n";
	        cout<<"\t\t\t\t|   __      __   ___  | |   ___    ___    _ __ ___     ___  |"<< "\n";
			cout<<"\t\t\t\t|   \\ \\ /\\ / /  / _ \\ | |  / __|  / _ \\  | '_ ` _ \\   / _ \\ |"<< ""<<endl;
			cout<<"\t\t\t\t|    \\ V  V /  |  __/ | | | (__  | (_) | | | | | | | |  __/ |"<<" \n";
			cout<<"\t\t\t\t|     \\_/\\_/    \\___| |_|  \\___|  \\___/  |_| |_| |_|  \\___| |"<< " \n";
            cout<<"\t\t\t\t =========================================================="<< "     \n";
            cout<<"\t\t\t\t\n"<<"     ^..^      /"<< "\t\t\t\tWelcome to the Quiz Game!\t"<<"     __";
            cout<<"\t\t\t\t\n"<<"     /_/\\_____/"<< "\t\t\t\t\t1. Start Game\t\t"<<"          __/o \\_";
            cout<<"\t\t\t\t\n"<<"        /\\   /\\"<< "\t\t\t\t\t2. How to Play\t\t"<<"          \\____  \\";
            cout<<"\t\t\t\t\n"<<"       /  \\ /  \\"<< "\t\t\t\t3. Exit\t\t"<<"                      /   \\";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                __   //\\   \\"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             __/o \\-//--\\   \\_/"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             \\____  ___  \\  |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                  ||   \\ |\\ |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                 _||   _||_||"<<"";
        	cout << endl;
  

    // Prompt the user to select an option
    cout <<"\nEnter your choice: ";
    cin >> choice;

}
int main() {

menu();
    
    
    
    return 0;
}

**Comment by Miracles01** [comment]
#include <iostream>
#include <string>
#include <conio.h>
#include <stdio.h>
using namespace std;

int choice;
void menu(){
     // Display the main menu options
    system("color 0B");//Color XY,X = สีของพื้นหลัง,Y=สีของข้อความ
    system("cls");
            cout<<"\t\t\t\t =========================================================="<< " \n";
	        cout<<"\t\t\t\t|   __      __   ___  | |   ___    ___    _ __ ___     ___  |"<< "\n";
			cout<<"\t\t\t\t|   \\ \\ /\\ / /  / _ \\ | |  / __|  / _ \\  | '_ ` _ \\   / _ \\ |"<< ""<<endl;
			cout<<"\t\t\t\t|    \\ V  V /  |  __/ | | | (__  | (_) | | | | | | | |  __/ |"<<" \n";
			cout<<"\t\t\t\t|     \\_/\\_/    \\___| |_|  \\___|  \\___/  |_| |_| |_|  \\___| |"<< " \n";
            cout<<"\t\t\t\t =========================================================="<< "     \n";
            cout<<"\t\t\t\t\n"<<"     ^..^      /"<< "\t\t\t\tWelcome to the Quiz Game!\t"<<"     __";
            cout<<"\t\t\t\t\n"<<"     /_/\\_____/"<< "\t\t\t\t\t1. Start Game\t\t"<<"          __/o \\_";
            cout<<"\t\t\t\t\n"<<"        /\\   /\\"<< "\t\t\t\t\t2. How to Play\t\t"<<"          \\____  \\";
            cout<<"\t\t\t\t\n"<<"       /  \\ /  \\"<< "\t\t\t\t3. Exit\t\t"<<"                      /   \\";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                __   //\\   \\"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             __/o \\-//--\\   \\_/"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             \\____  ___  \\  |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                  ||   \\ |\\ |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                 _||   _||_||"<<"";
        	cout << endl;
  

    // Prompt the user to select an option
    cout <<"\nEnter your choice: ";
    cin >> choice;

}
int main() {

menu();
    
    
    
    return 0;
}

**Comment by OHMSIRAPOB** [comment]
#include <iostream>
#include <string>
#include <conio.h>
#include <stdio.h>
#include <iomanip>
using namespace std;

int choice;
void menu(){
     // Display the main menu options
    system("color 0B");//Color XY,X = สีของพื้นหลัง,Y=สีของข้อความ
    system("cls");
	        cout<<"\n\n\n\t\t\t   __      __   ___  | |   ___    ___    _ __ ___     ___  "<<endl;
			cout<<"\t\t\t   \\ \\ /\\ / /  / _ \\ | |  / __|  / _ \\  | '_ ` _ \\   / _ \\ "<<endl;
			cout<<"\t\t\t    \\ V  V /  |  __/ | | | (__  | (_) | | | | | | | |  __/ "<<endl;
			cout<<"\t\t\t     \\_/\\_/    \\___| |_|  \\___|  \\___/  |_| |_| |_|  \\___| "<<endl;

	        cout<<"\033[47m\033[30m"<<"\t\t\t\t\n"<< "\t\t\t\t\tWelcome to the Quiz Game!\t"<< "\033[0m"<< "\033[36m"<<"             __";
            cout<<"\t\t\t\t\n"<< "\t\t\t\t\t\t1. Start Game\t\t"<<"          __/o \\_";
            cout<<"\t\t\t\t\n"<< "\t\t\t\t\t\t2. How to Play\t\t"<<"          \\____  \\";
            cout<<"\t\t\t\t\n"<< "\t\t\t\t\t\t3. Exit\t\t"<<"                      /   \\";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                __   //\\   \\"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             __/o \\-//--\\   \\_/"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                             \\____  ___  \\  |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                  ||   \\ |\\ |"<<"";
            cout<<"\t\t\t\t\t\t\n"<<"                                                                                 _||   _||_||"<<"";
        	cout << endl;

    cout <<"\t\t\tEnter your choice: ";
    cin >> choice;

}
int main() {

menu();
    
    
    
    return 0;
}

**Comment by OHMSIRAPOB** [comment]
ส่งเป็นไฟล์ให้ในช่องทางอื่น
